export type MetadataType = Metadata & ConvertedFields;

interface ConvertedFields {
  duration: number | null;
  height: number;
  width: number;
}

interface Metadata {
  SourceFile: string;
  ExifToolVersion: number;
  FileName: string;
  Directory: string;
  FileSize: string;
  FileModifyDate: string;
  FileAccessDate: string;
  FileInodeChangeDate: string;
  FilePermissions: string;
  FileType: string;
  FileTypeExtension: string;
  MIMEType: string;
  MajorBrand: string;
  MinorVersion: string;
  CompatibleBrands: string[];
  MovieHeaderVersion: number;
  CreateDate: string;
  ModifyDate: string;
  TimeScale: number;
  Duration: string;
  PreferredRate: number;
  PreferredVolume: string;
  PreviewTime: string;
  PreviewDuration: string;
  PosterTime: string;
  SelectionTime: string;
  SelectionDuration: string;
  CurrentTime: string;
  NextTrackID: number;
  TrackHeaderVersion: number;
  TrackCreateDate: string;
  TrackModifyDate: string;
  TrackID: number;
  TrackDuration: string;
  TrackLayer: number;
  TrackVolume: string;
  ImageWidth: number;
  ImageHeight: number;
  GraphicsMode: string;
  OpColor: string;
  CompressorID: string;
  SourceImageWidth: number;
  SourceImageHeight: number;
  XResolution: number;
  YResolution: number;
  BitDepth: number;
  PixelAspectRatio: string;
  VideoFrameRate: number;
  MatrixStructure: string;
  MediaHeaderVersion: number;
  MediaCreateDate: string;
  MediaModifyDate: string;
  MediaTimeScale: number;
  MediaDuration: string;
  MediaLanguageCode: string;
  HandlerDescription: string;
  Balance: number;
  AudioFormat: string;
  AudioChannels: number;
  AudioBitsPerSample: number;
  AudioSampleRate: number;
  HandlerType: string;
  HandlerVendorID: string;
  Encoder: string;
  MediaDataSize: number;
  MediaDataOffset: number;
  ImageSize: string;
  Megapixels: number;
  AvgBitrate: string;
  Rotation: number;
}
